const User = require("../models/userModel")
const jwt = require("jsonwebtoken")

// jwt consists of three parts: header (algorithm etc.), payload (nonsensitive user info), secret (generated by server)
const createToken = (_id) => {
  // first arg: payload object, second: secret key, third: opetions
  return jwt.sign({ _id }, process.env.SECRET_KEY, { expiresIn: "3d" })
}

// login user
const loginUser = async (req, res) => {
  const { email, password } = req.body

  try {
    const user = await User.login(email, password)
    const token = createToken(user._id)

    res.status(200).json({ email, token })
  } catch (error) {
    res.status(400).json({ error: error.message })
  }
}

//sign up user
const signupUser = async (req, res) => {
  const { email, password } = req.body

  try {
    const user = await User.signup(email, password)
    const token = createToken(user._id)

    res.status(200).json({ email, token })
  } catch (error) {
    res.status(400).json({ error: error.message })
  }
}

module.exports = { loginUser, signupUser }
